### ISSUE TITLE
Source map rewriting uses absolute paths instead of current directory

### ISSUE THREAD

**Issue by dpolivy** [labaneilers/hashly#35]
I'm playing with the source map rewriting (which is a great feature!), but finding the behavior is a bit different than I expected for the rewritten path.

Since the `.map` file is in the same directory as the source (and this is assumed in the code), the `sourceMappingURL` traditionally just includes the name of the map file without any pathing.

However, when the source map URL is rewritten, it ends up being done with the *full path, starting from `targetPath`*. This ends up breaking the sourcemap for me, since `targetPath` is NOT my wwwroot. Using the `sourceMapURLPrefix` option is one workaround, but it also requires me to know the wwwroot where the file will be hosted.

I think it might be better to default to leaving the source map without any path component at alll, just like in the source input. @hsingh23 any thoughts on this, since you originally wrote the code?

I'm happy to submit a PR but this is a "breaking" change.

**Comment by labaneilers** [comment]
I would love if you want to do a PR. I guess it would be a breaking change, kind of. If so, I think it would be fine to handle with a release note and semantic versioning.

I think I remember discussing this with @hsingh23, and that at that time, he couldn't get relative paths for the sourcemaps to work in Chrome. I think it would be a good idea to try again.

**Comment by hsingh23** [comment]
Hi @dpolivy, I'm cool with a PR. It's been a while since I worked on this, I think there was a reason we decided to go with targetPath. The line you probably want to change is https://github.com/labaneilers/hashly/blob/master/lib/hashly.js#L210 

It would be cool if the PR supported both targetPath and just file name via a switch.

**Comment by dpolivy** [comment]
Thanks, guys. I went ahead and submitted a PR which adds a new `--sourcemap-include-path` and `sourcemapIncludePath` option to handle this. Default behavior is consistent with current behavior so you don't need to treat it as a breaking change.
